---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm run build
  when:
    event:
    - push
    - tag

- name: upload-test-to-oss
  image: wangsiye/aliyun-ossutil:latest
  environment:
    OSS_KEY_ID:
      from_secret: aliyun_access_id
    OSS_KEY_SECRET:
      from_secret: aliyun_access_secret
  commands:
  - ossutil config  -L CH -e "oss-cn-shenzhen.aliyuncs.com" -i $OSS_KEY_ID -k $OSS_KEY_SECRET
  - ossutil cp -rf ./dist oss://dev-tool/aliyun-ecs
  when:
    event:
    - push

- name: deployment-to-oss
  image: wangsiye/aliyun-ossutil:latest
  environment:
    OSS_KEY_ID:
      from_secret: aliyun_access_id
    OSS_KEY_SECRET:
      from_secret: aliyun_access_secret
  commands:
  - ossutil config  -L CH -e "oss-cn-beijing.aliyuncs.com" -i $OSS_KEY_ID -k $OSS_KEY_SECRET
  - ossutil cp -rf ./dist oss://rancher2-drivers/pandaria/ui/node-driver-aliyun/${DRONE_TAG}
  when:
    event:
    - tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - dist/*
    prerelease: true
    title: "Pre-release ${DRONE_TAG}"
  when:
    event:
    - tag

node:
  instance: agent-amd64
